### ISSUE TITLE
 数据集是怎样的，images 和 masks直接放图片吗 

### ISSUE THREAD

**Issue by pingdow** [Jo-dsa/SemanticSeg#1]

**Comment by pingdow** [comment]
数据集是怎样的，images 和 masks直接放图片吗

**Comment by Jo-dsa** [comment]
I'm not sure to understand your question, but here are some precisions.
image: classic jpg image (RGB pixels)
mask: 2D image where each pixel is represented by its belonging class (ex: a 3x3 mask with 3 classes, 
`[[2,0,1],[0,1,0],[1,0,2]]`) 
which is later oneHot encoded (see `src/framework.py` code)

**Comment by Jo-dsa** [comment]
Closed
